# Generated by Django 3.1.7 on 2021-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0007_aula_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='youtube_id',
            field=models.CharField(max_length=32),
        ),
    ]
